## File Handling/Data Processing

#### Problem 1:
#### Problem Statement :
Define a function to read data from a text file
#### Constraints:
#### Test Cases :


In [1]:
def readFileData(filename):
    f = open(filename,'r') # r is to read the data
    filedata = f.readline() # Displays the first line of the file
    f.close()
    return filedata
readFileData('DataFiles/data.txt')

'Data in line 1\n'

In [2]:
def readFileData(filename):
    f = open(filename,'r')
    filedata = f.readline() # Displays the first line of file
    filedata += f.readline() # Second line appends with first line
    f.close()
    return filedata
readFileData('DataFiles/data.txt')

'Data in line 1\nData in line 2\n'

In [3]:
def readFileData(filename):
    f = open(filename,'r')
    filedata = f.read() # Reads the entire file
    f.close()
    return filedata
readFileData('DataFiles/data.txt')

'Data in line 1\nData in line 2\nData in line 3'

In [6]:
def readFileData(filename):
    with open(filename,'r') as f: #with allows to directly open and close the file instead of using close. f is a handler or descriptor.
        filedata = f.readline()
    return filedata
readFileData('DataFiles/data.txt')

'Data in line 1\n'

In [8]:
def readFileData(filename):
    with open(filename,'r') as f: #with allows to directly open and close the file instead of using close.
        for line in f:
            print(line,end='') #print understands the /n and space characters and prints the statements
    return
readFileData('DataFiles/data.txt')

Data in line 1
Data in line 2
Data in line 3

In [9]:
def readFileData(filename):
    with open(filename,'r') as f: #with allows to directly open and close the file instead of using close.
            print(f.read()) #print understands the /n and space characters and prints the statements.
                            #Instead of using for loop we can us f.read to print the entire file
    return
readFileData('DataFiles/data.txt')

Data in line 1
Data in line 2
Data in line 3


In [10]:
def writeIntoFile(filename,data):
    with open(filename,'w') as f: #w is to write the data
        f.write(data)
    return
writeIntoFile('DataFiles/fileWrite.txt','data written into fileWrite')

In [12]:
def writeIntoFile(filename,data,mode):
    with open(filename,mode) as f:
        f.write(data)
    return
writeIntoFile('DataFiles/fileWrite.txt','\nsecond line','a') # append will directly add new data to existing data

## Functional Programming

#### Problem 2
#### Problem Statement  :
Define a function to generate a marks data file for 1300 students such that each mark is entered in a new line.
Marks range from 0 to 100 (inclusive) as random numbers.


In [68]:
import random
def generateMarksData(n,filename):
    with open(filename,'w') as marksfile:
        for i in range(0,n):
            marks = random.randint(0,100)
            marksfile.write(str(marks)+'\n')
generateMarksData(1300,'DataFiles/marksData.txt')

#### Problem 3 :
#### Problem Statement :
Generate a report on the marks data with the following indicators.
* Highest Mark :
* Lowest Mark :
* Average Mark :
* No of students with distinction(>80):
* No of students with first class(>60):
* No of students with second class(>50):
* No of students with third class(>40):
* No of students failed(<40):

In [8]:
import random
def readMarksFromFile(filename):
    marks_li=[]
    with open(filename,'r') as f:
        for x in f:
            marks_li.append(int(x))
    writeMarksIntoFile('DataFiles/reportFile.txt',marks_li)
def writeMarksIntoFile(filename,arr):
    dist = 0
    first = 0
    second = 0
    third = 0
    fail = 0
    with open(filename,'w') as reportFile:
        reportFile.write("Highest is: "+str(max(arr))+'\n')
        reportFile.write("Lowest is: "+str(min(arr))+'\n')
        reportFile.write("Average is: "+str(sum(arr)//len(arr))+'\n')
        for i in range(0,len(arr)):
            if(arr[i]>=80):
                dist = dist+1
            elif(arr[i]>=60 and arr[i]<80):
                first = first+1
            elif(arr[i]>=50 and arr[i]<60):
                second = second+1
            elif(arr[i]>=40 and arr[i]<50):
                third = third + 1
            else:
                fail = fail+1
        reportFile.write("Distinction : "+str(dist)+'\n')
        reportFile.write("First class : "+str(first)+'\n')
        reportFile.write("Second class : "+str(second)+'\n')
        reportFile.write("Third class : "+str(third)+'\n')
        reportFile.write("Failed : "+str(fail)+'\n')
    return
readMarksFromFile('DataFiles/marksData.txt')

In [7]:
import re, timeit
def generateMarksReport(marksfile):
    start = timeit.default_timer()
    marksdata = readMarksFromFile(marksfile)
    return timeit.default_timer() - start
generateMarksReport('DataFiles/marksData.txt')

0.006674660000044241

In [58]:
li =[1,2,3,4,5,6]
#s = str(li)
s = list(map(str,li))
s[0]

'1'

In [60]:
def squares(n):
    return n*n
li =[1,2,3,4,5,6]
s = list(map(squares,li))
s[5]

36

In [63]:

s = [float(i) for i in s]
s

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

In [65]:
import timeit
start = timeit.default_timer()
li = [1,2,3,4,5,6]
s = list(map(str,li))
s = [float(i) for i in s]
print(timeit.default_timer()-start)

0.0001488880006945692


## External Libraries
#### SciPy.org

In [70]:
import numpy as np
a =np.array([0,1,2])
print(a)
type(a)

[0 1 2]


numpy.ndarray

In [71]:
import numpy as np
a =np.array([[0,1,2],[3,4,5]])
print(a)
type(a)

[[0 1 2]
 [3 4 5]]


numpy.ndarray